name: iris_pipeline

channels:
    - astropy

dependencies:
    - python
    - astropy
    - cfitsio
    - cython
    - gcc_linux-64
    - pip
    - pip:
      - sphinx-astropy
      - https://github.com/spacetelescope/jwst/archive/0.13.7.zip
