name: iris_pipeline

channels:
    - conda-forge

dependencies:
    - python
    - astropy
    - cfitsio
    - cython
    - gcc_linux-64
    - pip
    - pip:
      - sphinx-astropy
      - git+https://github.com/oirlab/tmt-crds.git
      - git+https://github.com/spacetelescope/jwst@0.17.0
